-- Completed 03/18/2024
local vC_AppName, vC_App = ...
if not ( vC_Run_MarkingBar ) then return end
-------------------------------------------------------
-- Declarations
-------------------------------------------------------
local vC_CountDownNumber					= 10					-- Countdown is defaulted 10 Sec, Max is 3600s (1h) for Coutndown
-------------------------------------------------------
-- Marking Bar Toggles
-------------------------------------------------------
function vC_MarkingBar()
	if ( InCombatLockdown() ) then return end

	if (( IsInGroup() or IsInRaid() ) and UnitIsGroupLeader("player") ) then
		vC_MarkingBarFrame:Show()
		vC_MarkingBarPing:Show()
	else
		vC_MarkingBarFrame:Hide()
		vC_MarkingBarPing:Hide()
	end
end
-------------------------------------------------------
-- Marking Bar Frame and Icons
-------------------------------------------------------
if ( vC_MarkingBarFrame == nil ) then
	local vC_MarkingBarFrame = CreateFrame("Frame", "vC_MarkingBarFrame", PlayerFrame, "BackdropTemplate")
		vC_SetBackdrop_Choice(vC_MarkingBarFrame, 47, 1)
		vC_MarkingBarFrame:EnableMouse(true)
		vC_MarkingBarFrame:SetSize(265, 34)
		vC_MarkingBarFrame:SetPoint("TOPLEFT", PlayerFrame, -53, 20)
		local vC_ReadyChk = CreateFrame("Button", "vC_ReadyChk", vC_MarkingBarFrame, "BackdropTemplate")
			vC_ReadyChk:SetSize(20, 20)
			vC_ReadyChk:SetPoint("LEFT", vC_MarkingBarFrame, "LEFT", 5, 0)
			vC_ReadyChk:SetNormalTexture(136814) --\\raidframe\\readycheck-ready
			vC_ReadyChk:GetNormalTexture():SetTexCoord(0,1,0,1)
			vC_ReadyChk:SetScript("OnClick", function(s) DoReadyCheck() end)
			vC_ReadyChk:SetScript("OnEnter", function(s) vC_cToolTips(s,1,1,"Ready Check") end)
			vC_ReadyChk:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
		local vC_CountDown = CreateFrame("Button", "vC_CountDown", vC_MarkingBarFrame, "BackdropTemplate")
			vC_CountDown:SetSize(28, 28)
			vC_CountDown:SetPoint("LEFT", vC_ReadyChk, "LEFT", 30, 0)
			vC_CountDown:SetNormalTexture(516773) -- \\HELPFRAME\\HelpIcon-ReportLag
			vC_CountDown:SetScript("OnClick", function(s) C_PartyInfo.DoCountdown(vC_CountDownNumber) end)
			vC_CountDown:SetScript("OnEnter", function(s) vC_cToolTips(s,1,1,vC_CountDownNumber.."s Countdown") end)
			vC_CountDown:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
		local vC_iconSkull = CreateFrame("Button", "vC_iconSkull", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconSkull:SetSize(20, 20)
			vC_iconSkull:SetPoint("LEFT", vC_CountDown, "RIGHT", 12, 0)
			vC_iconSkull:SetNormalTexture(137009)  -- \\targetingframe\\ui-raidtargetingicons
			vC_iconSkull:GetNormalTexture():SetTexCoord(0.75,1,0.25,0.5)
			vC_iconSkull:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 8) end)
		local vC_iconCross = CreateFrame("Button", "vC_iconCross", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconCross:SetSize(20, 20)
			vC_iconCross:SetPoint("LEFT", vC_iconSkull, "RIGHT", 3, 0)
			vC_iconCross:SetNormalTexture(137009)
			vC_iconCross:GetNormalTexture():SetTexCoord(0.5,0.75,0.25,0.5)
			vC_iconCross:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 7) end)
		local vC_iconSquare = CreateFrame("Button", "vC_iconSquare", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconSquare:SetSize(20, 20)
			vC_iconSquare:SetPoint("LEFT", vC_iconCross, "RIGHT", 3, 0)
			vC_iconSquare:SetNormalTexture(137009)
			vC_iconSquare:GetNormalTexture():SetTexCoord(0.25,0.5,0.25,0.5)
			vC_iconSquare:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 6) end)
		local vC_iconMoon = CreateFrame("Button", "vC_iconMoon", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconMoon:SetSize(20, 20)
			vC_iconMoon:SetPoint("LEFT", vC_iconSquare, "RIGHT", 3, 0)
			vC_iconMoon:SetNormalTexture(137009)
			vC_iconMoon:GetNormalTexture():SetTexCoord(0,0.25,0.25,0.5)
			vC_iconMoon:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 5) end)
		local vC_iconTriangle = CreateFrame("Button", "vC_iconTriangle", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconTriangle:SetSize(20, 20)
			vC_iconTriangle:SetPoint("LEFT", vC_iconMoon, "RIGHT", 3, 0)
			vC_iconTriangle:SetNormalTexture(137009)
			vC_iconTriangle:GetNormalTexture():SetTexCoord(0.75,1,0,0.25)
			vC_iconTriangle:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 4) end)
		local vC_iconDiamond = CreateFrame("Button", "vC_iconDiamond", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconDiamond:SetSize(20, 20)
			vC_iconDiamond:SetPoint("LEFT", vC_iconTriangle, "RIGHT", 3, 0)
			vC_iconDiamond:SetNormalTexture(137009)
			vC_iconDiamond:GetNormalTexture():SetTexCoord(0.5,0.75,0,0.25)
			vC_iconDiamond:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 3) end)
		local vC_iconCircle = CreateFrame("Button", "vC_iconCircle", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconCircle:SetSize(20, 20)
			vC_iconCircle:SetPoint("LEFT", vC_iconDiamond, "RIGHT", 3, 0)
			vC_iconCircle:SetNormalTexture(137009)
			vC_iconCircle:GetNormalTexture():SetTexCoord(0.25,0.5,0,0.25)
			vC_iconCircle:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 2) end)
		local vC_iconStar = CreateFrame("Button", "vC_iconStar", vC_MarkingBarFrame, "BackdropTemplate")
			vC_iconStar:SetSize(20, 20)
			vC_iconStar:SetPoint("LEFT", vC_iconCircle, "RIGHT", 3, 0)
			vC_iconStar:SetNormalTexture(137009)
			vC_iconStar:GetNormalTexture():SetTexCoord(0,0.25,0,0.25)
			vC_iconStar:SetScript("OnClick", function(s) SetRaidTargetIcon("target", 1) end)

	local vC_MarkingBarPing = CreateFrame("Frame", "vC_MarkingBarPing", vC_MarkingBarFrame, "BackdropTemplate")
		vC_SetBackdrop_Choice(vC_MarkingBarPing, 47, 1)
		vC_MarkingBarPing:EnableMouse(true)
		vC_MarkingBarPing:SetSize(175, 35)
		vC_MarkingBarPing:SetPoint("RIGHT", vC_MarkingBarFrame, "TOPRIGHT", 0, 15)
		local vC_iconQuestion = CreateFrame("Button", "vC_iconQuestion", vC_MarkingBarPing, "BackdropTemplate")
			vC_iconQuestion:SetSize(32, 32)
			vC_iconQuestion:SetPoint("LEFT", vC_MarkingBarPing, "LEFT", 2, 0)
			vC_iconQuestion:SetNormalTexture(616343)
			vC_iconQuestion:SetScript("OnEnter", function(s)
				--306 TOGGLEPINGLISTENER, 307 PINGATTACK, 308 PINGWARNING, 309 PINGONMYWAY, 310 PINGASSIST
				local key1, key2 = GetBindingKey("TOGGLEPINGLISTENER")
				vC_cToolTips(
					vC_iconQuestion,1,
					(
						"Your '|CFF00CCFFPing Radial Screen|r' keybind(s) are:\n\n"..
						"Keybind #1: "..(key1 ~= nil and key1 or "NONE").."\n"..
						"Keybind #2: "..(key2 ~= nil and key2 or "NONE")..
						((key1 == nil and key2 == nil) and "\n\nYou don't have anything keybinded." or "")
					)
				)
			end)
			vC_iconQuestion:SetScript("OnLeave", function(s) GameTooltip:Hide() end)
		local vC_iconPing = CreateFrame("Button", "vC_iconPing", vC_MarkingBarPing, "SecureActionButtonTemplate")
			vC_iconPing:SetSize(24, 24)
			vC_iconPing:SetPoint("LEFT", vC_iconQuestion, "RIGHT", 5, 0)
			vC_iconPing:SetNormalTexture(5215295)
			vC_iconPing:GetNormalTexture():SetTexCoord(0.330, 0.370, 0.164, 0.204)
			vC_iconPing:SetMouseClickEnabled(true)
			vC_iconPing:RegisterForClicks("AnyUp", "AnyDown")	
			vC_iconPing:SetAttribute("type","macro")
			vC_iconPing:SetAttribute("macrotext1","/ping [@target] Ping")
			vC_iconPing:SetScript("OnEnter", function(s)
				vC_cToolTips(s,1,1,"Ping!\n\nYou must have a target!")
			end)
			vC_iconPing:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
		local vC_iconHere = CreateFrame("Button", "vC_iconHere", vC_MarkingBarPing, "SecureActionButtonTemplate")
			vC_iconHere:SetSize(24, 24)
			vC_iconHere:SetPoint("LEFT", vC_iconPing, "RIGHT", 2, 0)
			vC_iconHere:SetNormalTexture(5215295)
			vC_iconHere:GetNormalTexture():SetTexCoord(0.915, 0.990, 0.075, 0.150)
			vC_iconHere:RegisterForClicks("AnyUp", "AnyDown")	
			vC_iconHere:SetAttribute("type","macro")
			vC_iconHere:SetAttribute("macrotext1","/ping [@target] On My Way")
			vC_iconHere:SetScript("OnEnter", function(s)
				vC_cToolTips(s,1,1,"On My Way!\n\nYou must have a target!")
			end)
			vC_iconHere:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
		local vC_iconWarn = CreateFrame("Button", "vC_iconWarn", vC_MarkingBarPing, "SecureActionButtonTemplate")
			vC_iconWarn:SetSize(24, 24)
			vC_iconWarn:SetPoint("LEFT", vC_iconHere, "RIGHT", 2, 0)
			vC_iconWarn:SetNormalTexture(5215295)
			vC_iconWarn:GetNormalTexture():SetTexCoord(0.478, 0.553, 0.295, 0.370)
			vC_iconWarn:RegisterForClicks("AnyUp", "AnyDown")    
			vC_iconWarn:SetAttribute("type","macro")
			vC_iconWarn:SetAttribute("macrotext1","/ping [@target] Warning")
			vC_iconWarn:SetScript("OnEnter", function(s)
				vC_cToolTips(s,1,1,"Warning!\n\nYou must have a target!")
			end)
			vC_iconWarn:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
		local vC_iconAttack = CreateFrame("Button", "vC_iconAttack", vC_MarkingBarPing, "SecureActionButtonTemplate")
			vC_iconAttack:SetSize(24, 24)
			vC_iconAttack:SetPoint("LEFT", vC_iconWarn, "RIGHT", 2, 0)
			vC_iconAttack:SetNormalTexture(5215295)
			vC_iconAttack:GetNormalTexture():SetTexCoord(0.765, 0.840, 0.075, 0.150)
			vC_iconAttack:RegisterForClicks("AnyUp", "AnyDown")    
			vC_iconAttack:SetAttribute("type1","macro")
			vC_iconAttack:SetAttribute("macrotext1","/ping [@targettarget] Attack")
			vC_iconAttack:SetAttribute("type2","macro")
			vC_iconAttack:SetAttribute("macrotext2","/target [@targettarget,harm]")
			vC_iconAttack:SetScript("OnEnter", function(s)
				vC_cToolTips(s,1,1,"Attack Away!  Kill 'em All!\n\nLEFT CLICK: Will point to what Tank is targeting!\n\nRIGHT CLICK: Will target to what Tank is targeting!")
			end)
			vC_iconAttack:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
		local vC_iconAssist = CreateFrame("Button", "vC_iconAssist", vC_MarkingBarPing, "SecureActionButtonTemplate")
			vC_iconAssist:SetSize(24, 24)
			vC_iconAssist:SetPoint("LEFT", vC_iconAttack, "RIGHT", 2, 0)
			vC_iconAssist:SetNormalTexture(5215295)
			vC_iconAssist:GetNormalTexture():SetTexCoord(0.765, 0.840, 0.000, 0.075)
			vC_iconAssist:RegisterForClicks("AnyUp", "AnyDown")    
			vC_iconAssist:SetAttribute("type","macro")
			vC_iconAssist:SetAttribute("macrotext1","/ping [@target] Assist")
			vC_iconAssist:SetScript("OnEnter", function(s)
				vC_cToolTips(s,1,1,"Need of Assist or Assist Someone!\n\nYou must have a target!")
			end)
			vC_iconAssist:SetScript("OnLeave", function(s) vC_cToolTips(0) end)
			
		vC_MarkingBar()
end